cucumber-json-formatter=${cucumber-json-formatter.version}
html-formatter=${html-formatter.version}
jackson=${jackson.version}
junit-xml-formatter=${junit-xml-formatter.version}
messages=${messages.version}
messages-cli=${project.version}
messages-ndjson=${messages-ndjson.version}
pretty-formatter=${pretty-formatter.version}
testng-xml-formatter=${testng-xml-formatter.version}
