name: cucumber-messages
title: Cucumber Messages CLI
# read version from tag using selective-checkout
adopt-info: cucumber-messages
summary: A commandline interface for working with Cucumber Messages
description: |
  Cucumber can output test results in newline delimited json format. This format can then be transformed into different reports. 
  
  This tool supports the conversion of cucumber messages into cucumber-json, html, junit-xml and testng-xml reports.

license: MIT AND Apache-2.0

website: https://github.com/cucumber/messages-cli
source-code: https://github.com/cucumber/messages-cli
contact: https://github.com/cucumber/messages-cli
issues: https://github.com/cucumber/messages-cli
donation: https://opencollective.com/cucumber

confinement: strict
base: core24
type: app

# Enable faster LZO compression
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  cucumber-messages:
    command: default/bin/cucumber-messages
    plugs:
      - home

parts:
  cucumber-messages:
    plugin: nil
    source: .
    build-attributes:
      - network
    override-pull: |
      set -o nounset
      
      # For core22 or newer bases:
      if ! craftctl default; then
         printf \
           'Error: Unable to run the default action of this step.\n' \
           1>&2
           exit 2
      fi
      
      if ! "${CRAFT_PROJECT_DIR}/snap/selective-checkout-v3.0.3/scriptlets/selective-checkout"; then
          printf \
              'Error: Unable to run the selective-checkout scriptlet.\n' \
              1>&2
              exit 2
      fi
    override-build: |
      cd java
      # Build the application.
      # - Testing happened locally, so skip it here
      # - The installed maven version is old, so skip the enforcer
      mvn package -DskipTests -Denforcer.skip=true
      cp -r target/maven-jlink/default $SNAPCRAFT_PART_INSTALL
    build-packages:
      # cucumber-messages dependencies
      - maven
      - mesa-libgallium
      - libllvm20
      - openjdk-21-jdk-headless
      # selective-checkout dependencies
      - curl
      - jq
      - sed
      - git


lint:
  ignore:
    - library:
        - default/lib/*.so
