name: Release GitHub

permissions: { }

on:
  push:
    branches: [release/*]

jobs:
  create-github-release:
    name: Create GitHub Release and push distribution packages
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cucumber/action-create-github-release@cf2c6f77ba35d2424362e83393a1c4c004cf2ddb # v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: JReleaser Assemble
        run: mvn -DskipTests -Pjreleaser package jreleaser:assemble jreleaser:full-release
        working-directory: java
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.CUKEBOT_MESSAGES_CLI_JRELEASER_TOKEN }}
          JRELEASER_GITHUB_USERNAME: cukebot
